### ISSUE TITLE
Ubuntu with Blender docker image

### ISSUE THREAD

**Issue by Tilix4** [zocker-160/blender-docker#3]
Hi,

I'm about to create a docker image as a linux distro (ubuntu) with Blender installed in. I need it for my app template CICD: https://gitlab.com/superprod/stax_suite/stax and I cannot find any up-to-date image or open repo with dockerfiles fulfilling my needs.

In a will to keep things together, I'd like to propose it to your repo, is it related to what you're dealing with here?

**Comment by zocker-160** [comment]
Hi,

I am so sorry for this super late reply, but I have not gotten any notification by GitHub for some reason :(.

So yes my repo here contains Dockerfiles that create images with Blender inside based on Debian slim. 
Feel free to use it for whatever you want.

Regarding Ubuntu: currently I am not willing to maintain Ubuntu images on top of all the Debian ones, which already take up a lot of time to maintain.
But adapting the base images to Ubuntu should be easy to do though.

**Comment by zocker-160** [comment]
closed due to inactivity
